# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5828a1cbadcb19c85ba7fc6f18d7b22c866d82d95745c71323b58ae86777410d5f90d33ebc8c245229b69a60b62eccb16e7865ff2cc05e466e403faec8e86f1f

test:
  secret_key_base: 227d734d92bdb591f7d49713c9e0c6cf185b861b033f0b86dc5be1d2fb48c70fd658c5138b2453b6c9587fb19126ea0af350c5b2e3764bdc84b0197e1a5534c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
